/**
 * Weak-password blocklist for signup validation (ISSUE-004 DoD).
 *
 * Source: top entries from SecLists / RockYou aggregated lists. We include
 * the top ~200 most common passwords (the long tail past ~500 has rapidly
 * diminishing fraud value but bigger bundle cost). The check is
 * case-insensitive — `Password1` is rejected for the same reason as
 * `password1`.
 *
 * NOT a comprehensive password strength meter — that's a separate concern
 * (zxcvbn-style scoring would be over-engineering for v1). Three guards:
 *   1. Min length 8 (Zod, in register route)
 *   2. NOT in this blocklist
 *   3. NOT trivially predictable (3+ repeated chars, sequential digits) —
 *      caught by `looksTrivial`
 *
 * Returns `true` if the password is weak (should be rejected).
 */

const COMMON_PASSWORDS = new Set<string>(
  [
    '123456',
    '123456789',
    'password',
    '12345678',
    '12345',
    '1234567',
    'qwerty',
    'abc123',
    '111111',
    '123123',
    'admin',
    'letmein',
    'welcome',
    'monkey',
    'login',
    'passw0rd',
    'master',
    'hello',
    'freedom',
    'whatever',
    'qazwsx',
    'trustno1',
    '1q2w3e4r',
    '654321',
    'jordan23',
    'harley',
    'password1',
    'robert',
    'matthew',
    'jordan',
    'asshole',
    'daniel',
    'andrew',
    'lakers',
    'andrea',
    'buster',
    'joshua',
    '1234',
    '12345678910',
    '987654321',
    'iloveyou',
    'sunshine',
    'princess',
    'football',
    'baseball',
    'dragon',
    '1q2w3e',
    'q1w2e3r4',
    'starwars',
    'computer',
    'michelle',
    'jessica',
    'pepper',
    '1111',
    'zxcvbn',
    'mickey',
    'aaaaaa',
    'pussy',
    'fuckyou',
    'fucker',
    'shadow',
    'hottie',
    'loveme',
    'zaq12wsx',
    'hockey',
    'thomas',
    'tigger',
    'access',
    '696969',
    'mustang',
    'batman',
    'test',
    'pass',
    'angel',
    '1qaz2wsx',
    'orange',
    'killer',
    '696969',
    'soccer',
    'liverpool',
    'william',
    'matrix',
    'flower',
    'jonathan',
    'familia',
    'familia1',
    'amor',
    'amor1234',
    'cambio',
    'casa',
    'gabriel',
    'gabriel1',
    'maria',
    'maria1',
    'jose',
    'jose1234',
    'mexico',
    'argentina',
    'colombia',
    'venezuela',
    'chile',
    'peru',
    'iloveu',
    'iloveyou1',
    'iloveyou2',
    'mama',
    'papa',
    'familia',
    'qwerty123',
    'qwertyuiop',
    'asdf1234',
    'asdfgh',
    'zxcv1234',
    'football1',
    'baseball1',
    'soccer1',
    'tennis',
    'hockey1',
    'killer1',
    'monkey1',
    'shadow1',
    'master1',
    'mustang1',
    'changeme',
    'changeit',
    'temp1234',
    'temporary',
    'guest',
    'demo',
    'sample',
    'qwerty1',
    'p@ssw0rd',
    'p@ssword',
    'pa$$word',
    'pa$$w0rd',
    'password!',
    'password12',
    'password123',
    'password1234',
    'admin123',
    'admin1234',
    'root',
    'toor',
    'qwertyu',
    'qwertyui',
    'asdfghj',
    'asdfghjk',
    'zxcvbnm',
    'abc12345',
    'abcd1234',
    'abcdef',
    'abcdefg',
    'abcdefgh',
    '11111111',
    '00000000',
    '0000',
    '1111',
    '2222',
    '3333',
    '4444',
    '5555',
    '6666',
    '7777',
    '8888',
    '9999',
    'aaaa',
    'bbbb',
    'cccc',
    'dddd',
    'eeee',
    'ffff',
    'iloveu1',
    'qwer1234',
    'asdf',
    'zxcv',
    'wasd',
    'wasd1234',
    'admin1',
    'admin12',
    'admin01',
    'administrator',
    'sysadmin',
    'super',
    'super123',
    'superman',
    'batman1',
    'spiderman',
    'pokemon',
    'pokemon1',
    'minecraft',
    'fortnite',
    'roblox',
    'gamer',
    'gamer1',
    'gamer123',
    'noob',
    'pro',
    'pro123',
    'baby',
    'kitten',
    'puppy',
    'cute',
    'cutie',
    'love',
    'love1',
    'love12',
    'love123',
    'love1234',
    'lovely',
    'happy',
    'happy1',
    'sunshine1',
    'sunshine123',
    'rainbow',
    'butterfly',
    'flower1',
    'rose',
    'tulip',
    'orchid',
    'cat',
    'dog',
    'bird',
    'fish',
    'rabbit',
    'hamster',
    'dragon1',
    'phoenix',
    'unicorn',
    'tiger',
    'lion',
    'ninja',
    'samurai',
    'wizard',
    'warrior',
    'hunter',
    '123qwe',
    'qwe123',
    '1q2w3e',
    '1qaz',
    '2wsx',
    '3edc',
    'p4ssw0rd',
    'p455w0rd',
    'h@ckme',
    'letmein1',
    'letmein123',
  ].map((p) => p.toLowerCase())
);

const TRIVIAL_PATTERNS = [
  /(.)\1{3,}/, // 4+ repeated char ("aaaa", "1111")
  /^0+$/, // all zeros
  /^(?:0123|1234|2345|3456|4567|5678|6789|7890|9876|8765|7654|6543|5432|4321|3210)\d*$/, // ascending/descending sequences
];

function looksTrivial(password: string): boolean {
  return TRIVIAL_PATTERNS.some((re) => re.test(password));
}

/**
 * Returns true when `password` is considered weak and should be rejected.
 * Case-insensitive lookup against COMMON_PASSWORDS + heuristic patterns.
 */
export function isWeakPassword(password: string): boolean {
  const lower = password.toLowerCase();
  if (COMMON_PASSWORDS.has(lower)) return true;
  if (looksTrivial(lower)) return true;
  return false;
}

/** Exposed for testing — caller-facing API is `isWeakPassword`. */
export const __TEST_ONLY__ = {
  COMMON_PASSWORDS,
  looksTrivial,
};
