/**
 * Week Sheets Schema — E-021 per 06_DATA_MODEL.md.
 *
 * Sheet del scope Week. La semana arranca en domingo en la TZ del user
 * (convención US/LatAm — Sunday = start of week). Helper para resolver
 * el "domingo de" una fecha cualquiera vive en
 * `src/lib/domain/week-calc.ts`.
 *
 * BR-7: exactly one WeekSheet per (user, week_starting). Enforced via
 * UNIQUE index at the DB layer.
 *
 * Shape: kickoff fields (capturados domingo al planear semana) + review
 * fields (capturados sábado al cerrar). Algunos JSONB para estructuras
 * complejas (calendar_blocks, people_to_connect, self_care,
 * review_post_mortem) — la validación full de esas shapes vive en
 * ISSUE-033 (week screen wire), aquí solo type-stubs vía Drizzle.
 *
 * Linked: BR-7, FT-034, FT-035, US-033.
 */

import {
  pgTable,
  text,
  uuid,
  date,
  smallint,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './users';

// JSONB payload shapes (loose; full Zod validation in ISSUE-033).
export interface CalendarBlock {
  winIndex: number;
  day: number; // 0..6 (Sun..Sat)
  timeBlock: 'morning' | 'afternoon' | 'evening' | 'night';
  time?: string; // HH:mm optional
}

export interface PersonToConnect {
  name: string;
  why: string;
}

export interface SelfCare {
  rest?: string;
  move?: string;
  eat?: string;
  sleep?: string;
}

export interface ReviewPostMortem {
  // Generated by the agent layer later. Loose for now.
  highlights?: string[];
  blockers?: string[];
  notes?: string;
}

export const weekSheets = pgTable(
  'week_sheets',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /** Sunday in user TZ. Resolved via `weekStartingFor()` before insert. */
    weekStarting: date('week_starting').notNull(),

    // ── Kickoff (Sunday) ──────────────────────────────────────────────
    /** "Si solo una cosa pasa esta semana, ¿cuál?" */
    oneThing: text('one_thing'),

    /** Up to 3 wins for the week. Max enforced at DB. */
    threeWins: text('three_wins').array(),

    /** [{ winIndex, day, timeBlock, time? }] — when each win is scheduled. */
    calendarBlocks: jsonb('calendar_blocks').$type<CalendarBlock[]>(),

    /** [{ name, why }] — relational intent for the week. */
    peopleToConnect: jsonb('people_to_connect').$type<PersonToConnect[]>(),

    /** Free text. */
    learnOne: text('learn_one'),
    avoidOne: text('avoid_one'),

    /** { rest, move, eat, sleep } — self-care commitments. */
    selfCare: jsonb('self_care').$type<SelfCare>(),

    /** Set by app when kickoff fields are complete. */
    kickoffCompletedAt: timestamp('kickoff_completed_at', {
      mode: 'date',
      withTimezone: true,
    }),

    // ── Review (Saturday) ─────────────────────────────────────────────
    reviewWins: text('review_wins').array(),
    reviewLessons: text('review_lessons').array(),
    /** 1..10 — enforced via DB CHECK. */
    reviewEnergy: smallint('review_energy'),
    /** Single-sentence wrap-up. */
    reviewOneSentence: text('review_one_sentence'),
    /** Auto-generated post-mortem from the agent layer (later). */
    reviewPostMortem: jsonb('review_post_mortem').$type<ReviewPostMortem>(),
    reviewedAt: timestamp('reviewed_at', { mode: 'date', withTimezone: true }),

    createdAt: timestamp('created_at', { mode: 'date', withTimezone: true }).notNull().defaultNow(),

    updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    // BR-7: exactly one sheet per (user, week_starting).
    uniqueIndex('week_sheets_user_week_unique').on(table.userId, table.weekStarting),
    // "últimas N semanas" hot path.
    index('week_sheets_user_week_desc_idx').on(table.userId, sql`${table.weekStarting} DESC`),
  ]
);

export type WeekSheet = typeof weekSheets.$inferSelect;
export type NewWeekSheet = typeof weekSheets.$inferInsert;
